name: BTC-5m-Scanner

on:
  schedule:
    # Jalan setiap 5 menit
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-btc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install ccxt pandas requests
      - name: Run
        run: python btc_bot.py # Pastikan nama filenya sama
